# Array and there dimension and more


In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# convert list into array

import numpy as np
x = [1,2,3,4]
y= np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
#to check if its array or not

import numpy as np
x = [1,2,3,4,5]
y=np.array(x)
y

array([1, 2, 3, 4, 5])

In [6]:
# we have an empty list and apppend some values in it , and then convert that list into array

l=[]

for i in range(1,5):
    a= input("enter any : ")
    l.append(a)                       # appends into list l whatever input  we store in a variable

print(np.array(l))            # printing array after converting list into array

enter any :  rajat
enter any :  rohit
enter any :  vishal
enter any :  ankit


['rajat' 'rohit' 'vishal' 'ankit']


In [9]:
# obove program has one mistake whatver input we give it takes a string , so just int also before input 
l=[]

for i in range(1,5):
    a= int(input("enter any : "))           # converting string into int as input
    l.append(a)                             # appends into list l whatever input  we store in a variable

print(np.array(l))                           # printing array after converting list into array

enter any :  1
enter any :  2
enter any :  34
enter any :  56


[ 1  2 34 56]


In [10]:
# check dimendion of an array:

import numpy as np
x = [1,2,3,4]
y= np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [14]:
# creating 2 d array

ar2= np.array([[1,2,3,4],[5,6,7,8]])       # ar2 is varibale  amd taking two list and both the list should have same no of data items
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [17]:
# creating 3 d array 

ar3= np.array([[[1,2,3,4],[5,6,7,8],[1,5,5,7]]])       # ar3 is varibale  amd taking two list and all three list should have same no of data items
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [1 5 5 7]]]
3


In [18]:
# Multi dimension array

arn = np.array([1,2,3,4], ndmin =10 )
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
