# special type of arrays

In [12]:
# 1 -  zero 0's arrays

import numpy as np
ar_zero = np.zeros(4)    # zeros is a function to fill all the element in array with 0  and       4 is to give 4 element in 1 D array
ar_zero1 = np.zeros((3,4))         # 3,4 means 2D array with 3 rows and 4 columns filled with zeros
print(ar_zero)
print()                             # to give one blank space
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [13]:
ar_one = np.ones(4)                  # one is a function to fill all the element in array with 1
ar_one1 = np.ones((3,4))             # # 3,4 means 2D array with 3 rows and 4 columns filled with ones
print(ar_one)
print()
print(ar_one1)


[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty array

In [14]:
ar_en = np.empty(4)
print(ar_en)                     # whatever previous memory was there in an array will be stored in empty array
                                # as example just previously we have tried with ones array , the previous memory has 1 array element
                               # so oen array element will stored in empty array

[1. 1. 1. 1.]


# range of Elements

In [15]:
ar_rn = np.arange(5)      # arange function is same like range function from 0 to n-1
print(ar_rn)

[0 1 2 3 4]


# create diagonal element with 1

In [17]:
ar_diag = np.eye(3)     # eye is a function for diagonal element filled with 1 nd here 3 means 3 by 3 array
ar_diag1 = np.eye(3,5)       # here 3,5 means 3 rows 5 columns and diagonal element filled with 1
print(ar_diag)
print()
print(ar_diag1)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Create an array with values that are spaced linearly in a specified interval

In [18]:
ar_lin = np.linspace(0,10, num= 5)     # linspace is function to give same gap between all elements
                                       # ( 0,10,num =5 ) means range will be from 0 to 10 but only 5 elemnts

print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
