# Creating random valued array

# rand() - function used to genrate a random value between 0 and 1

In [2]:
import numpy as np
var = np.random.rand(4)                 # 4 is value od 1 d array
var1 = np.random.rand(2,5)              # for 2 d array 2 rows and 5 columns
print(var)
print()
print(var1)

[0.35216635 0.79708177 0.84945978 0.47052846]

[[0.14540998 0.93679257 0.17985315 0.4176601  0.67719071]
 [0.73003131 0.5112962  0.08228671 0.37591928 0.31860794]]


# randn() - the function is used to generate random value close to zero can be positive and negative


In [4]:
import numpy as np
var=np.random.randn(4)
print(var)

[ 1.14334896 -0.54103225  0.27797765 -0.3461832 ]


# ranf() - this also give specified value in between 0 and 1 but 0 is included and 1 is not included i.e [0.0 , 1.0)

In [5]:
import numpy as np
var=np.random.ranf(4)
print(var)

[0.32570789 0.66882331 0.55120889 0.69163537]


# randint() - this return a random number between the given range

In [6]:
import numpy as np
var=np.random.randint(5,20,5)                # range is 5 to 20 and total elements 5 should be there in range 5 to 20
print(var)

[17  5 14 12 10]
