# data type in arrays -- function is dtype

In [4]:
import numpy as np
var = np.array([1,2,3,4,12,13,14,15])
print(" Data type is : ", var.dtype)
print()
print(var)

 Data type is :  int32

[ 1  2  3  4 12 13 14 15]


In [5]:
import numpy as np
var = np.array([1.0,2.0,3.2,5.6])
print(" Data type is : ", var.dtype)
print()
print(var)

 Data type is :  float64

[1.  2.  3.2 5.6]


In [6]:
import numpy as np
var = np.array(["A","S","D","F",0,1,2,3])
print(" Data type is : ", var.dtype)
print()
print(var)

 Data type is :  <U11

['A' 'S' 'D' 'F' '0' '1' '2' '3']


# convert one data type to another

In [11]:
x= np.array([1,2,3,4])
print("data type is ", x.dtype)

# int 32 to int8

x1=np.array([1,2,3,4], dtype = np.int8)
print("data type is : " , x1.dtype)

data type is  int32
data type is :  int8


# int to float

In [14]:
x= np.array([1,2,3,4],dtype = "f")
print("data type is ", x.dtype)
print(x)

data type is  float32
[1. 2. 3. 4.]


# data type can be used a sunction also

In [15]:
x= np.array([1,2,3,4])
new=np.float32(x)
print("data type is ", x.dtype)
print("data type is ", new.dtype)
print(x)
print(new)

data type is  int32
data type is  float32
[1 2 3 4]
[1. 2. 3. 4.]


# directly tansfer one data type to another

In [16]:
x= np.array([1,2,3,4])
new=x.astype(float)

print(x)
print(new)

[1 2 3 4]
[1. 2. 3. 4.]
