In [2]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([[1,2],[1,2]])

print(var)
print()

print(var1)
print()

print(var.shape)         #will tell you the shape i.e 1 D array with 4 element
print(var1.shape)        # its 2d array ( 2 rows, 2 elemensts)

[1 2 3 4]

[[1 2]
 [1 2]]

(4,)
(2, 2)


# Multidimesnsional array

In [3]:
import numpy as np
var = np.array([1,2,3,4],ndmin = 4)        # ndmin is 4 dimension array
print(var)
print(var.shape)                           # here output is  (1,1,1,4)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [13]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,10])       # ndmin is 4 dimension array
print(var)
print()
x=var.reshape(5,4)  
print(x)

[ 1  2  3  4  5  6  7  8  9  0  1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


In [15]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,10])       
print(var)                                                       # 1 D array
print(var.ndim)
print()                                                         # empty line print
x=var.reshape(5,4)  
print(x)
print()
print(x.ndim)                                                   # 2 d array

[ 1  2  3  4  5  6  7  8  9  0  1  2  3  4  5  6  7  8  9 10]
1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]

2


In [23]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])       
print(var)                                                       # 1 D array
print(var.ndim)
print()                                                         # empty line print
x=var.reshape(4,3,1)  
print(x)
print()
print(x.ndim)                                                   # 2 d array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]

3
