# Numpy sirthmetic operations

# add  np.add(a+b)

In [11]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = var + 3
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [4 5 6 7]


In [28]:
import numpy as np
x = np.array([1,2,3,4,5])
x1 = np.array([1,2,3,4,5])
var = x+x1
print(var)

[ 2  4  6  8 10]


# subtract

In [29]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = var - 3
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [-2 -1  0  1]


# Multiply

In [30]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = var * 3
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [ 3  6  9 12]


# Divide

In [31]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = var / 3
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [0.33333333 0.66666667 1.         1.33333333]


# mod  a%b

In [32]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = var % 3
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [1 2 0 1]


# power a**b

In [33]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = var ** 3
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [ 1  8 27 64]


In [35]:
import numpy as np
x = np.array([1,2,3,4,5])
x1 = np.array([1,2,3,4,5])
var = x**x1
print(var)

[   1    4   27  256 3125]


# reciprocal 1/a

In [50]:
import numpy as np
var = np.array([1,2,3,4])
print("the var output is ", var)
var1 = np.reciprocal(var)
print("the var1 output is : ", var1)

the var output is  [1 2 3 4]
the var1 output is :  [1 0 0 0]


# 2d array addition

In [41]:
import numpy as np 
x = np.array([[1,2,3,4],[1,2,3,4]])
y = np.array([[1,2,3,4],[1,2,3,4]])
z = np.add(x,y)
print(z)


[[2 4 6 8]
 [2 4 6 8]]


In [45]:
import numpy as np 
x = np.array([[1,2,3,4],[1,2,3,4]])
y = np.array([[1,2,3,4],[1,2,3,4]])
z = x*y
print(z)


[[ 1  4  9 16]
 [ 1  4  9 16]]


In [46]:
#divide 
import numpy as np 
x = np.array([[1,2,3,4],[1,2,3,4]])
y = np.array([[1,2,3,4],[1,2,3,4]])
z = x/y
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
#mod 
import numpy as np 
x = np.array([[1,2,3,4],[1,2,3,4]])
y = np.array([[1,2,3,4],[1,2,3,4]])
z = x/y
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
#power 

import numpy as np 
x = np.array([[1,2,3,4],[1,2,3,4]])
y = np.array([[1,2,3,4],[1,2,3,4]])
z = x**y
print(z)

[[  1   4  27 256]
 [  1   4  27 256]]
