# indexing Numpy arrays

In [3]:
# 1 D array

import numpy as np
x = np.array([1,2,3,4])

print(x[0])
print(x[1])

1
2


In [5]:
# 2 D array

import numpy as np
x = np.array([[1,2,3,4],[1,2,3,4]])

print(x[0])
print(x[1])

print()

print(x[0,1])
print(x[1,3])


[1 2 3 4]
[1 2 3 4]

2
4


In [12]:
# 3d array 
import numpy as np
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)

print()

print(x[0,0,1])
print(x[0,1,3])
print(x[0,2,0])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

2
8
9


In [20]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])       
print(var)                                                       # 1 D array

print()                                                         # empty line print
x=var.reshape(4,3,1)  
print(x)

# we want to fetch 3,5,9,10

print(x[0,2,0])
print(x[1,1,0])
print(x[2,2,0])
print(x[3,0,0])


[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
3
5
9
10
