# array slicing


In [2]:
# 1 d array slicing

import numpy as np
x = np.array([1,2,3,4,5,6,7])
print(x)
print()

# we want to fecth from 2 to 5 

print("slice from 2 to 5 : " , x[1:5])      # here 1 is the indec no of 2 i,e starting point and 5 is the stop point at which no we want to stop

[1 2 3 4 5 6 7]

slice from 2 to 5 :  [2 3 4 5]


In [5]:
import numpy as np
x = np.array([1,2,3,4,5,6,7])
print(x)
print()

# we want to fecth from 2 to 5 but jumpy by 1 no i.e we want to 2 and 4 to print

print("slice from 2 to 5 : " , x[1:5:2])  

[1 2 3 4 5 6 7]

slice from 2 to 5 :  [2 4]


In [18]:
# 2 d array

import numpy as np
x = np.array([[9,8,7,6],[2,3,4,5]])
print(x)
print()

print(x[0,1:2])

[[9 8 7 6]
 [2 3 4 5]]

[8]
