# iterating Numpy arrays

In [2]:
# for 1 D array

import numpy as np
x = np.array([1,2,3,4])
print()
print(x)
print()

for i in x:
    print(i)
    


[1 2 3 4]

1
2
3
4


In [4]:
# 2 D array

import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print()

for i in x:
    print(i)
    

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]


In [5]:
# iteration inside iteration
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print()

for i in x:
    print(i)

print()

for j in x:
    for k in j:
        print(k)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [6]:
# if we dont want to use for loop we can use function i.e nditer()

import numpy as np
x = np.array([[1,2,3],[8,9,0]])
for i in np.nditer(x):
    print(i)

1
2
3
8
9
0


In [8]:
# changing the data type with the help of buffere flag to give spaces and op_dtype to pass argumnet to change the data type
import numpy as np
x = np.array([[1,2,3],[8,9,0]])
for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'8'
b'9'
b'0'


In [13]:
# iteration using step size , from array [1,2,3,4,5,6,7,8[ we want 1  skipping element

import numpy as np
x = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(x[:, ::2]):
    print(i)

1
3
5
7


In [14]:
# enumeration function - matching sequence no of something one by one
# using function ndenumerate() --- gives you the index value also

import numpy as np
x = np.array([1,2,3,4,7,9])
for idx,i in np.ndenumerate(x):
    print(idx,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 7
(5,) 9


In [15]:
# for 2 D array

import numpy as np
x = np.array([[1,2,3,4,7,9],[45,67,78,99,11,99]])
print(x)
print()
for idx,i in np.ndenumerate(x):
    print(idx,i)

[[ 1  2  3  4  7  9]
 [45 67 78 99 11 99]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 7
(0, 5) 9
(1, 0) 45
(1, 1) 67
(1, 2) 78
(1, 3) 99
(1, 4) 11
(1, 5) 99
