# numpy copy and view

In [2]:
# copy - the copy should not affect by the changes made in the original array and function is copy()

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]= 42
print(x)
print(arr)

[1 2 3 4 5]
[42  2  3  4  5]


In [3]:
# viwew - the view should be affected if there are made changes in the orignal array

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]= 42
print(x)
print(arr)

[42  2  3  4  5]
[42  2  3  4  5]
