# Numpy array join and split function

In [4]:
# join array 1D

import numpy as np

x = np.array([1,2,3,4])
y = np.array([13,5,7,8])

z= np.concatenate((x,y))
print(z)

[ 1  2  3  4 13  5  7  8]


In [6]:
# 2d array

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[13,5],[7,8]])

z= np.concatenate((x,y),axis=1)
z1= np.concatenate((x,y),axis=0)
print(z)
print()
print(z1)

[[ 1  2 13  5]
 [ 3  4  7  8]]

[[ 1  2]
 [ 3  4]
 [13  5]
 [ 7  8]]


In [10]:
#using stack function - it is same as concatanetion only difference is it works alsong axis--- stck()
import numpy as np

x = np.array([1,2,3,4])
y = np.array([13,5,7,8])

z= np.stack((x,y),axis = 1)           # stacking along axis
print(z)

print()

z1 =  np.stack((x,y))                # stacking over one another
print(z1)

[[ 1 13]
 [ 2  5]
 [ 3  7]
 [ 4  8]]

[[ 1  2  3  4]
 [13  5  7  8]]


In [15]:
# stacking along rows, columns,height/depth 
# 1. htack() - stacking alsong rows
# 2. vstack() - stacking alsong columns
# 3. dstack() - stacking alsong height

x = np.array([1,2,3,4])
y = np.array([13,5,7,8])

z= np.hstack((x,y))
print(z)

print()

z1 = np.vstack((x,y))
print(z1)

print()

z2 = np.dstack((x,y))
print(z2)

[ 1  2  3  4 13  5  7  8]

[[ 1  2  3  4]
 [13  5  7  8]]

[[[ 1 13]
  [ 2  5]
  [ 3  7]
  [ 4  8]]]
