# search , sort ,searched sorted and filter operation in numpy arrays

In [1]:
# search  user where() method
# find the index value where 4 is there
import numpy as np
x = np.array([1,2,3,4,5,6,4,5,6,4])
y = np.where(x==4)
print(y)

(array([3, 6, 9], dtype=int64),)


In [2]:
# where th values are odd
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.where(x%2 == 0)
print(y)


(array([1, 3, 5, 7, 9], dtype=int64),)


In [3]:
# where th values are even
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.where(x%2 == 1)
print(y)

(array([0, 2, 4, 6, 8], dtype=int64),)


# Search sorted  - method searchsorted()
# If we want to insert the value in an array, and then array should be in sorted form , then it return the index value where we can place the element

In [6]:
# find th index value where 7 can be inserted

import numpy as np
x = np.array([6,7,8,9])
y = np.searchsorted(x,7)
print(y)

1


# search from right side by default we search from left side --- for right side #### side='right' 

In [7]:
import numpy as np
x=np.array([6,7,8,9])
y=np.searchsorted(x,7,side='right')
print(y)

2


In [10]:
# Multiple values

# find the index value where 2 ,4,and 6 should be inserted

import numpy as np
x=np.array([1,3,8,7])
y=np.searchsorted(x,[6,7])
print(y)

[2 2]


# sort-- putting elements in a sequence no-- by sort() function


In [11]:
# sort an element

import numpy as np
x=np.array([3,2,6,1])
y=np.sort(x)
print(y)

[1 2 3 6]


In [19]:
# sort a string
# we can sort the string or boolean

import numpy as np
x=np.array(['banana','cherry', 'cherry1','apple'])
y=np.sort(x)
print(y)

['apple' 'banana' 'cherry' 'cherry1']


In [14]:
# sort bollean
import numpy as np
x=np.array(['True','False','False'])
y=np.sort(x)
print(y)

['False' 'False' 'True']


# Filter array---- Filtering

In [ ]:
# getting some elements out of an existing array and creating a new array out of them is called filtering
# In numpy you filter an array using a boolean index list

# If the value at index is True then that element is contained in filtered array
# If the value at index is False then that element is executed from  filtered array

In [23]:
# to get  a and f from an array

import numpy as np
var = np.array(['a' , 's', 'd' , 'f' ])
x= [True, False , False, True]
new_var = var[x]
print(new_var)

['a' 'f']
