# Airthmetics functions

In [4]:
# shuffle

import numpy as np
x = np.array([1,2,3,4,5])
np.random.shuffle(x)
print(x)

[4 2 1 3 5]


In [19]:
# shuffle

import numpy as np
x = np.array([1,2,3,4,5])
y=np.random.shuffle(x)
print(y)      # output None because shuffle modifies the list directly and it return None
print(x)

None
[3 2 1 5 4]


In [22]:
# shuffle

import numpy as np
x = np.array([1,2,3,4,5])
y=np.random.shuffle(x)
y=x                    # then it will work
print(y)      # output None because shuffle modifies the list directly and it return None


[3 4 2 1 5]


In [9]:
import numpy as np
x = np.arange(16).reshape((4,4))
np.random.shuffle(x)
print(x)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]]


In [15]:
#unique

import numpy as np
x= np.array([1,2,3,4,5,6,2,3,2,4,2])
y=np.unique(x,return_index=True,return_counts=True)
print(y)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([1, 4, 2, 2, 1, 1], dtype=int64))


In [26]:
# resize = change the shape of an array

import numpy as np
x = np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))                      # here (2,3) is shape in whihc we want o change 2 = rows and 3 is element in each row
print(y)

[[1 2 3]
 [4 5 6]]


In [28]:
# Flatten - to convert 2D into 1 D array
import numpy as np
x = np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))                      # here (2,3) is shape in whihc we want o change 2 = rows and 3 is element in each row
print(y)

print()

z=y.flatten()
print(z)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [29]:
#if we want to give order

import numpy as np
x = np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))                      # here (2,3) is shape in whihc we want o change 2 = rows and 3 is element in each row
print(y)

print()

z=y.flatten(order='F')
print(z)

[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]


In [36]:
import numpy as np
x = np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))                      # here (2,3) is shape in whihc we want o change 2 = rows and 3 is element in each row
print(y)

print()

z=y.flatten(order='F')
print(z)
print(y.ravel())

[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]
[1 2 3 4 5 6]
