# insert and Delete Functions

In [1]:
# insert

import numpy as np
x=np.array([1,2,3,4])
y=np.insert(x,2,40)           # 2 is the index value where we have to insert , and 40 is the value which we have to insert
print(y)

[ 1  2 40  3  4]


In [3]:
# value to be inserted at multiple index
import numpy as np
x=np.array([1,2,3,4])
print(x)
print()
y=np.insert(x,(2,4),40)           
print(y)

[1 2 3 4]

[ 1  2 40  3  4 40]


In [5]:
# float value - it does not insert float value will take integer value only
import numpy as np
x=np.array([1,2,3,4])
print(x)
print()
y=np.insert(x,(2,4),6.5)           
print(y)

[1 2 3 4]

[1 2 6 3 4 6]


In [9]:
# 2D array

In [7]:
import numpy as np
x=np.array([[1,2,3],[1,2,3]])
print(x)
print()
y=np.insert(x,1,6,axis=0)           
print(y)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [6 6 6]
 [1 2 3]]


In [8]:
x=np.array([[1,2,3],[1,2,3]])
print(x)
print()
y=np.insert(x,1,6,axis=1)           
print(y)

[[1 2 3]
 [1 2 3]]

[[1 6 2 3]
 [1 6 2 3]]


In [10]:
# delete function
import numpy as np
x=np.array([1,2,3,4])
y=np.delete(x,3)               # 3 is the index value at which needs to be deleted
print(y)

[1 2 3]
