# Numpy matrix and Array Matrix 

In [7]:
# Matrix Multiplication
import numpy as np
x= np.matrix([[1,2],[2,3]])
y=np.matrix([[4,5],[6,7]])
print(x)
print()
print(type(x))
print(y)
print()
print(type(y))
print()
print(x*y)
print((x*y).shape)

[[1 2]
 [2 3]]

<class 'numpy.matrix'>
[[4 5]
 [6 7]]

<class 'numpy.matrix'>

[[16 19]
 [26 31]]
(2, 2)


In [6]:
# array Multiplication
import numpy as np
x= np.array([[1,2],[2,3]])
y=np.array([[4,5],[6,7]])
print(x)
print()
print(type(x))
print(y)
print()
print(type(y))
print()
print(x*y)
print((x*y).shape)

[[1 2]
 [2 3]]

<class 'numpy.ndarray'>
[[4 5]
 [6 7]]

<class 'numpy.ndarray'>

[[ 4 10]
 [12 21]]
(2, 2)


In [9]:
# matrix Multiplication by dot function
import numpy as np
x= np.matrix([[1,2],[2,3]])
y=np.matrix([[4,5],[6,7]])
print(x)
print()
print(type(x))
print(y)
print()
print(type(y))
print()
print(x*y)
print((x*y).shape)
print()
print(x.dot(y))                                        # dot function

[[1 2]
 [2 3]]

<class 'numpy.matrix'>
[[4 5]
 [6 7]]

<class 'numpy.matrix'>

[[16 19]
 [26 31]]
(2, 2)

[[16 19]
 [26 31]]
