# Matrix Functions

In [6]:
# transpose matrix

import numpy as np
x = np.matrix ([[1,2,3],[4,5,6]])
print(x)
print()
print(x.shape)
print()
y=np.transpose(x)
print(y)
print()
print(y.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)

[[1 4]
 [2 5]
 [3 6]]

(3, 2)


In [10]:
# swapaxes
x = np.matrix ([[1,2,3],[4,5,6]])
print(x)
print()
print(x.shape)
print()
y=np.swapaxes(x,0,1)               # axis 0 converts into axis 1
print(y)

[[1 2 3]
 [4 5 6]]

(2, 3)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
# inverse matrix
x = np.matrix ([[1,2],[3,4]])
print(x)
print()
print(x.shape)
print()
y=np.linalg.inv(x)
print(y)

[[1 2]
 [3 4]]

(2, 2)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
# power matrix  

import numpy as np
x= np.matrix([[1,2],[2,3]])
print(x)
print()
print(type(x))
print()
y=np.linalg.matrix_power(x,0)        # when power is 0 its identity matrix
print(y)
print()
z=np.linalg.matrix_power(x,-2)
print(z)






[[1 2]
 [2 3]]

<class 'numpy.matrix'>

[[1 0]
 [0 1]]

[[13. -8.]
 [-8.  5.]]


In [25]:
# determinate of a maytrix
x= np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print()
print(type(x))
print()

y= np.linalg.det(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

<class 'numpy.matrix'>

0.0


In [ ]:
import numpy as np
temp= np.array([1,2,3,4,5,6,7,8,9])
x= np.reshape(temp,(3 , 3))
print(x)